### ISSUE TITLE
Run application error

### ISSUE THREAD

**Issue by nicolalopatriello** [a8t/guitar-tuner#10]
Hi, 
after `npm install` when i execute `npm run dev` i receive the following error:
`
 10% building modules 1/1 modules 0 activeGenerating SSL Certificate  94% asset optimization                                                                 
 ERROR  Failed to compile with 2 errors                                                                20:39:36

 error  in ./src/components/Tuner/TunerDisplayNeedle.vue

Module build failed: TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:132:14)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:147:30)

 @ ./src/router/index.js 4:0-71
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

 error  in ./src/components/Tuner/TunerDisplayStrobe.vue

Module build failed: TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:132:14)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/home/nik/Desktop/rob/guitar-tuner/node_modules/eslint/lib/util/traverser.js:144:34)

 @ ./src/router/index.js 5:0-71
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js
                                                                                                    `

any idea?

Thanks

N

**Comment by a8t** [comment]
Hi Nik, thanks for filing this – made me realize that the README asks for npm installation vs yarn, which I've been using. if you could do a clean clone + yarn install to see if that fixes the issue, I'd appreciate that!

I'm not 100% sure that it would fix the problem but that jumped out @ me. Please LMK!

**Comment by nicolalopatriello** [comment]
Ok perfect, with yarn install and next npm run dev the app starts.
Now seems that i've another problem, i open another issue.
Thanks!
